# ~/.config/starship.toml
# Compact two-line prompt configuration

add_newline = false
command_timeout = 1000
format = """$directory$git_branch$git_status$line_break$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = '…/'
home_symbol = '~'
read_only_style = '197'
read_only = '  '
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style)'
truncation_symbol = '…/'
style = 'bold green'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'bold yellow'
conflicted = '='
ahead = '⇡${count}'
diverged = '⇕'
behind = '⇣${count}'
untracked = '?${count}'
stashed = "$${count}"
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'

[kubernetes]
disabled = true

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "
disabled = true

[vagrant]
format = "via [ vagrant $version]($style) "
disabled = true

[docker_context]
format = "via [ $context](bold blue) "
disabled = true

[helm]
format = "via [ $version](bold purple) "
disabled = true

[python]
symbol = " "
python_binary = "python3"
disabled = true

[nodejs]
format = "via [ $version](bold green) "
disabled = true

[ruby]
format = "via [ $version]($style) "
disabled = true
